repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "fc26039" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.19.1
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
